version: "2"
networks:
  staticnymc:
    ipam:
      config:
        - subnet: 172.20.1.0/24
          gateway: 172.20.1.1
volumes:
    node_modules:
    mongo_data:
services:
  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db/mongo
      - /etc/localtime:/etc/localtime
    restart: always
    networks:
      staticnymc:
        ipv4_address: 172.20.1.2
  nodejs:
    build: ./app/be
    ports:
      - "4000:4000"
    volumes:
      - ./app:/usr/share/nginx/html
      - node_modules:/usr/share/nginx/html/be/node_modules
      - /etc/localtime:/etc/localtime
    restart: always
    depends_on:
      - mongo
    networks:
      staticnymc:
        ipv4_address: 172.20.1.3
    links:
      - mongo:mongo
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
      - ./nginx/ca/server.key/:/etc/nginx/server.key:ro
      - /etc/localtime:/etc/localtime
    restart: always
    depends_on:
      - nodejs
    networks:
      staticnymc:
        ipv4_address: 172.20.1.4
    links:
      - nodejs:__DOCKER_BE_NODEJS__
