#FROM node:10.17.0-alpine3.10
FROM node:8.17.0-alpine3.9
LABEL MAINTAINER ymc-github <yemiancheng@gmail.com>
ENV PROJECT_DIR=/usr/share/nginx/html/be
WORKDIR $PROJECT_DIR
#CMD ["npm", "run" ,"pm2"]
CMD ["npm", "run" ,"start"]